### ISSUE TITLE
Aztarna path for Dockerfile COPY

### ISSUE THREAD

**Issue by mitchallain** [vmayoral/robot_hacking_manual#1]
Hi vmayoral, thanks for putting this together.

It may be helpful to instruct in the readme that users clone/copy the `aztarna` package to the Dockerfile build directory (`basic_robot_cybersecurity/robot_footprinting/tutorial1`) for tutorial 1 so that it can be copied via the relative path (`COPY ./aztarna /root/aztarna`) in the Dockerfile.

**Comment by vmayoral** [comment]
Thanks @MitchAllain, how about sending a PR with that contribution?

**Comment by vmayoral** [comment]
@MitchAllain, I'm kindly closing this up since [`aztarna`](https://github.com/aliasrobotics/aztarna)is not maintained anymore. The tutorial is left for reference and further questions can be forwarded to Alias Robotics, if any.
