### ISSUE TITLE
Docker File for ROS 1 case study

### ISSUE THREAD

**Issue by 929937690** [vmayoral/robot_hacking_manual#2]
Hello,
Do we have a Dockerfile setup for the ROS 1 case study? We have a docker file for other cases but not on ROS 1. 

And a minor issue on the main ReadMe file is that hyperlinks for the Robot Operating system and TurtleBot 3 are mixed up. ROS 1 routes to TurtleBot 3 page and TurtleBot 3 routes to ROS 1 page.

**Comment by vmayoral** [comment]
>  Do we have a Dockerfile setup for the ROS 1 case study? We have a docker file for other cases but not on ROS 1.

See https://github.com/vmayoral/robot_hacking_manual/tree/master/1_case_studies/4_ros

> And a minor issue on the main ReadMe file is that hyperlinks for the Robot Operating system and TurtleBot 3 are mixed up. ROS 1 routes to TurtleBot 3 page and TurtleBot 3 routes to ROS 1 page.

Can you please send a Pull Request fixing this?

**Comment by 929937690** [comment]
For ROS 2 case study example, the docker file is provided: https://github.com/vmayoral/robot_hacking_manual/blob/master/1_case_studies/2_ros2/Dockerfile

But docker file for ROS 1 is empty:
https://github.com/vmayoral/robot_hacking_manual/blob/master/1_case_studies/4_ros/Dockerfile

**Comment by 929937690** [comment]
Done for sending pull request on ReadMe file

**Comment by vmayoral** [comment]
> Done for sending pull request on ReadMe file

Thanks for #3.

> But docker file for ROS 1 is empty:
https://github.com/vmayoral/robot_hacking_manual/blob/master/1_case_studies/4_ros/Dockerfile

Very true. I might've missed that while disclosing stuff. Official Docker images should do (nothing fancy in the setup there, unless you want to install additional tools to play around). Having a Docker image starting with

```Dockerfile
FROM ros:melodic
```

or similar (depending on which version you'd like to pentest) would do.

**Comment by 929937690** [comment]
I am running this case study on my local machine. But the reception rate is not affected at all. I am running the roscore, a talker, and a listener along with the python script for fin ack attack, and set the iface to "ens33" which I am using for my ROS master. 

And do you still have a copy of the docker file or image so I test it over there and see if the reception rate has changed?

**Comment by vmayoral** [comment]
Dockerfile is trivial for this particular case study. What you seem to be looking is consulting help. Closing this ticket as the original issue has been addressed. 

The particular example you're referring to was life-demonstrated at https://www.youtube.com/watch?v=jo_L9Ra8UqU and various other talks. Docker networking is hard, make sure you're getting it right. If you need consulting help, reach out [Alias Robotics](https://aliasrobotics.com/ask-for-information.php) for professional help.
